### ISSUE TITLE
Request Timestamp should be set when the request is created

### ISSUE THREAD

**Issue by sortelli** [amzn/amazon-pay-sdk-ruby#14]
The `Timestamp` parameter sent with each request is create once, when the `Client` is initialized. This causes requests made with that client to return `RequestExpired` errors when waiting a small amount of time between creating the client and using it.

The expected state is for each request to submit the current time that the request was issued as the `Timestamp` parameter, rather than the time that the client was instantiated.

**Comment by sortelli** [comment]
I've submitted a pull request with a suggested fix: https://github.com/amzn/amazon-pay-sdk-ruby/pull/15

**Comment by bjguillot** [comment]
Thanks for bringing this to our attention.  We will take a look.

**Comment by sortelli** [comment]
Thank you for merging my PR!
