### ISSUE TITLE
IpnHandler: NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by lucasfais** [amzn/amazon-pay-sdk-ruby#17]
Since 2018 April 29, `IpnHandler` is raising a `NoMethodError` exception at `lib/amazon_pay/ipn_handler.rb:227`, `validate_subject` method.

https://github.com/amzn/amazon-pay-sdk-ruby/blob/e43652be72c63f9d6423620b1341f7d23b65a193/lib/amazon_pay/ipn_handler.rb#L224-L232

I have simulated the same code on console:

```ruby
16] pry(main)> OpenSSL::X509::Certificate.new(cert_pem)
=> #<OpenSSL::X509::Certificate
 subject=#<OpenSSL::X509::Name CN=sns.amazonaws.com>,
 issuer=#<OpenSSL::X509::Name CN=Amazon,OU=Server CA 1B,O=Amazon,C=US>,
 serial=#<OpenSSL::BN 12507411336474143690653958489236113070>,
 not_before=2018-03-06 00:00:00 UTC,
 not_after=2019-03-06 12:00:00 UTC>
[17] pry(main)> OpenSSL::X509::Certificate.new(cert_pem).subject
=> #<OpenSSL::X509::Name CN=sns.amazonaws.com>
[18] pry(main)> OpenSSL::X509::Certificate.new(cert_pem).subject.to_a
=> [["CN", "sns.amazonaws.com", 19]]
```

The problem is that the code is trying to access the 4th position from the `subject` array, but it actually doesn't exist.

I'm not sure why that suddenly changed. Maybe SNS service started to use a different certificate? I don't know.

**Comment by bjguillot** [comment]
Thanks for reporting this.   We're looking into this right now.

**Comment by lucasfais** [comment]
I did some more tests and I've confirmed that certificate is different now. With the old one, the `subject` array was like this:

```ruby
[["C", "US", 19], ["ST", "Washington", 12], ["L", "Seattle", 12], ["O", "Amazon.com, Inc.", 12], ["CN", "sns.amazonaws.com", 12]]
```

**Comment by bjguillot** [comment]
The AWS/SNS team is in the process of deploying certificates to fix the problem.  It may take a few hours for the deployment to complete.  Please let me know tomorrow if you are still encountering the issue.

**Comment by lucasfais** [comment]
Yes, it is fixed. Thank you.

I opened PR #18 just to share the monkey patch we have used in the meantime. It works for both certificates and don't raise `NoMethodError` if the information is missing. Feel free to merge it or not.

**Comment by lucasfais** [comment]
Fixed with https://github.com/amzn/amazon-pay-sdk-ruby/commit/39808f2404188588f0224a142f84c08a95f8e63b

**Comment by bjguillot** [comment]
@lucasfais while we went with a different approach for the fix in the SDK, I do want to thank you for pointing out this issue on Monday.
