### ISSUE TITLE
Can't sign payloads for button signatures

### ISSUE THREAD

**Issue by justin-robinson** [amzn/amazon-pay-sdk-ruby#23]
As a ruby Amazon Pay user I want to be able to generate signatures for Amazon Pay buttons.

Currently only PHP, .Net, Node, and Java are supported in the [Amazon Pay docs](https://amazonpaycheckoutintegrationguide.s3.amazonaws.com/amazon-pay-recurring-checkout/add-the-amazon-pay-button.html)

We can follow the procedures outlined by Amazon Pay [here](https://amazonpaycheckoutintegrationguide.s3.amazonaws.com/amazon-pay-api-v2/signing-requests.html#step-2-create-a-string-to-sign) to generate the signature

**Comment by shangamesh** [comment]
This SDK is targeted to serve Amazon pay merchants which uses CV1 (i.e Checkout V1 flow). In CV1 flow, merchant wont use PublicKey & PrivateKey. Only for CV2 (i.e Checkout V2 flow) , merchants will pass PublicKey & PrivateKey which is not expected for this SDK.

For more info please refer following documents :
CV1 - https://developer.amazon.com/docs/amazon-pay-onetime/register.html
CV2 - https://amazonpaycheckoutintegrationguide.s3.amazonaws.com/amazon-pay-checkout/get-set-up-for-integration.html
