### ISSUE TITLE
Signature for button

### ISSUE THREAD

**Issue by zenati** [amzn/amazon-pay-sdk-ruby#26]
Hello, this is a serious probleme because so many people lose so many hours trying to figure out how to generate the signature for the V2. I know that this SDK is for v1 only. But what is it useful for if v2 is now standard.

I already saw the issue https://github.com/amzn/amazon-pay-sdk-ruby/issues/23.

But you closed it. For me closing the issue is not the solution, a simpler way to sign a payload is the solution.

**Comment by shangamesh** [comment]
Hi 
I understand that you are seeking for having simplified method or utility to create signature for button. 
You can use the following Github repository : https://github.com/amazonpay-labs/amazonpay-sample-ruby-v2 where we provide utility [method](https://github.com/amazonpay-labs/amazonpay-sample-ruby-v2#amazon-pay%E3%83%9C%E3%82%BF%E3%83%B3%E3%81%AEsignature%E3%81%AE%E7%94%9F%E6%88%90) to create signature for V2.

Let us know if that is helping to solve your problem

**Comment by shangamesh** [comment]
You can refer this [guide](https://developer.amazon.com/docs/amazon-pay-api-v2/signing-requests.html) to create signature on your own if you dont want to use our SDK or can create utility/helper in your code base by following this [commit](https://github.com/amzn/amazon-pay-sdk-ruby/pull/24/commits/0c1987cf95ad549ae9f33c003761587bdd66a732)

Alternative approach :
There is some developer have created ruby [sdk](https://github.com/bytenaija/amazon-pay-sdk-ruby) for V2 which can be used to tackle your problem. Please note that Amazon Pay didnt developed this SDK but it was created by some developer to help other developers who uses ruby as programming language to integrate with amazon pay
